# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="BARBIE"
MODULE_VERSION="0.16"


inherit perl-module

DESCRIPTION="Validate a META.json file within a CPAN distribution."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Test-CPAN-Meta-0.250.0
	>=dev-perl/Test-Pod-Coverage-1.100.0
	>=dev-perl/JSON-2.900.0
	>=dev-perl/Test-Pod-1.510.0
	dev-lang/perl"
