# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="ETHER"
MODULE_VERSION="0.030"


inherit perl-module

DESCRIPTION="simulate/test networking via LWP::UserAgent"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Test-Requires
	dev-perl/Test-Fatal
	dev-perl/HTTP-Date
	dev-perl/HTTP-Message
	>=dev-perl/Test-Warnings-0.16.0
	dev-perl/Test-RequiresInternet
	>=dev-perl/Test-Deep-1.120.0
	dev-perl/libwww-perl
	dev-perl/URI
	dev-perl/Path-Tiny
	dev-perl/Safe-Isa
	dev-perl/Try-Tiny
	>=dev-perl/namespace-clean-0.260.0
	dev-lang/perl"
