# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.9

EAPI=5

MODULE_AUTHOR="TOBYINK"
MODULE_VERSION="0.009"


inherit perl-module

DESCRIPTION="simplified clone of smartmatch operator"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/Exporter-Tiny-0.42.0
	>=perl-gcpan/Sub-Infix-0.004
	dev-perl/Test-Fatal
	dev-lang/perl"
