# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="PWR"
MODULE_VERSION="0.06"


inherit perl-module

DESCRIPTION="CloudFlare Dynamic DNS"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/JSON-Any-1.380.0
	dev-perl/Moo
	>=dev-perl/Readonly-1.30.0
	dev-lang/perl"
